#!/bin/bash
LANG=en_US.UTF-8; NULL=/dev/null

if which checkScripts > $NULL 2>&1; then
    check64bits  || exit
    checkScripts || exit
else
    echo 'Please add pathes for scrispts and data to $PATH.'
    exit
fi

if [ $# -lt 1 ]; then
    echo ""
    echo "usage : $0  Number_of_elements  [filename]"
    echo ""
    echo "   ex) $ N=10000; random.awk \$N | ./debug \$N"
    echo ""
    exit
else
    rm -f data* tmp* sorted*
    N=$1; shift
    if [ $# -eq 0 ]; then
        data=data$$
        cat - > data$$      # read data from stdin
    else
        data=$1; shift
    fi
fi

sort $data > sorted$$
for i in 3 h a g k; do
    Release/cSort -N $N -$i $data > tmp$$
    if ! diff sorted$$ tmp$$ > /dev/null; then
        echo "-$i option doesn't work."
    diff tmp$$ sorted$$
    exit
    fi
done
